titles:
- titulo: Rats
  year: 2018
  link: https://www.youtube.com/watch?v=C_ijc7A5oAc
  grupo:
    nombre: Ghost
    fundacion: 2006
    componentes:
     - Tobias Forge (Cardinal Copia)
     - Un grupo de Ghouls Sin Nombre
  disco:
    nombre: Prequelle
    release: 2018
    tracks:
      - Ashes
      - Rats
      - Faith
      - See the Light
      - Miasma (Instrumental)
      - Dance Macabre
      - Pro Memoria
      - Witch Image
      - Helvetesfönster
      - Life Eternal

- titulo: Wishmaster
  year: 2000
  link: https://www.youtube.com/watch?v=eJTlH521E6w
  grupo:
    nombre: Nightwish
    fundacion: 1996
    componentes:
      - Tuomas Holopainen
      - Tarja Turunen
      - Jukka Nevalainen
      - Sami Vänskä
      - Emppu Vuorinen
  disco:
    nombre: Wishmaster
    release: 2000
    tracks:
      - She is My Sin
      - The Kinslayer
      - Come Cover Me
      - Wanderlust
      - Two for Tragedy
      - Wishmaster
      - Bare Grace Misery
      - Crownless
      - Deep Silent Complete
      - Dead Boy's Poem
      - Fantasmic
      - Sleepwalker

- titulo: Rasputin
  year: 2007
  link: https://www.youtube.com/watch?v=cdkBs0VCSX0
  grupo:
    nombre: Turisas
    fundacion: 1997
    componentes:
      - Mathias Nygard
      - Jussi Wickström
      - Tude Lehtonen
      - Netta Skog
      - Olli Vanska
  disco:
    nombre: The Varangian Way, edición especial
    release: 2007
    tracks:
      - To Holmgard and Beyond
      - A portage to the Unknown
      - Cursed Be Iron
      - Fields of Gold
      - In the Court of Jarisleif
      - Five Hundred and One
      - The Dnieper Rapids
      - Miklagard Overture
      - Rasputin
      - To Holmgard and Beyond, single edit

- titulo: Blind and Frozen
  year: 2017
  link: https://www.youtube.com/watch?v=2N4tXf3Ensw
  grupo:
    nombre: Beast in Black
    fundacion: 2015
    componentes:
      - Yannis Papadopoulos
      - Anton Kabanen
      - Kasperi Heikkinen
      - Mate Molnar
      - Sami Hanninen
  disco:
    nombre: Berserker
    release: 2017
    tracks:
      - Beast in Black
      - Blind and Frozen
      - Blood of a Lion
      - Born Again
      - Zodd The Immortal
      - The Fifth Angel
      - Crazy, Mad, Insane
      - Hell for All Eternity
      - Eternal Fire
      - Go to Hell
      - End of the World
      - Ghost in the Rain

- titulo: Traveller in Time
  year: 1990
  link: https://www.youtube.com/watch?v=QYLpSTclFUU
  grupo:
    nombre: Blind Guardian
    fundacion: 1984
    componentes:
      - Hansi Kursch
      - Andre Olbrich
      - Marcus Siepen
      - Thomas Stauch
  disco:
    nombre: Tales from the Twillight World
    release: 1990
    tracks:
      - Traveller in Time
      - Welcome to Dying
      - Weird Dreams
      - Lord of the Rings
      - Goodbye My Friend
      - Lost in the Twillight Hall
      - Tommyknockers
      - Altair 4
      - The Last Candle
      - Run for the Night

- titulo: Dragula
  year: 1998
  link: https://www.youtube.com/watch?v=EqQuihD0hoI
  grupo:
    nombre: Rob Zombie
    fundacion: 1998
    componentes:
      - Rob Zombie
      - John Tempesta
      - Mige Riggs
      - Blasko
  disco:
    nombre: Hellbilly Deluxe
    release: 1998
    tracks:
      - Call of the Zombie
      - Superbeast
      - Dragula
      - Living Dead Girl
      - Perversion 99
      - Demonoid Phenomenoid
      - Spookshow Baby
      - How to Make a Monster
      - Meet the Creeper
      - The Ballad of Resurrection Joe and Rosa Whore
      - What Lurks on Channel X?
      - Return of the Phantom Stranger
      - The Beginning of the End